# Generated by Django 3.2 on 2021-04-16 21:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banreason',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Причины блокировки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Man'), (0, 'Woman')], default=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='respect',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Репутация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Подпись'),
        ),
    ]
