# Generated by Django 3.2 on 2021-04-17 17:02

import django.db.models.deletion
import easy_thumbnails.fields
import userena.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20210417_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True,
                                                                         help_text='A personal image displayed in your profile.',
                                                                         upload_to=userena.models.upload_to_mugshot,
                                                                         verbose_name='mugshot')),
                ('privacy',
                 models.CharField(choices=[('open', 'Open'), ('registered', 'Registered'), ('closed', 'Closed')],
                                  default='registered', help_text='Designates who can view your profile.',
                                  max_length=15, verbose_name='privacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile',
                                              to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'permissions': (('view_profile', 'Can view profile'),),
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete'),
            },
        ),
    ]
