# Generated by Django 3.2 on 2021-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
