# Generated by Django 3.2 on 2021-04-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_user_last_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_online',
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
