# Generated by Django 3.2 on 2021-04-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='reputation',
            name='subject',
            field=models.TextField(null=True, verbose_name='Причина изменения репутации'),
        ),
    ]
