# Generated by Django 3.2 on 2021-04-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20210420_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_rep',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='reputation',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_rep',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
