# Generated by Django 3.2 on 2021-04-22 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_auto_20210421_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.PositiveIntegerField(default=1000, verbose_name='Деньги форума'),
        ),
        migrations.AlterField(
            model_name='reputation',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_rep',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='reputation',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_rep',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
