# Generated by Django 3.2 on 2021-04-22 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0011_auto_20210422_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Значение')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата добавления')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Комментарий перевода')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='from_transaction', to=settings.AUTH_USER_MODEL,
                                                verbose_name='Получатель')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='to_transaction', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Денежный перевод',
                'verbose_name_plural': 'Денежные переводы',
            },
        ),
    ]
