# Generated by Django 3.2 on 2021-04-24 19:32

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_moneytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respect_pagination', models.PositiveSmallIntegerField(default=15,
                                                                        verbose_name='Колличество записей изменения репутации на странице')),
                ('transact_pagination',
                 models.PositiveSmallIntegerField(default=15, verbose_name='Колличетсво транзакций на странице')),
                ('ico_range_numbers', django.contrib.postgres.fields.ranges.IntegerRangeField(null=True,
                                                                                              verbose_name='Диапазон пользовательских иконок чата')),
                ('nik_price', models.PositiveSmallIntegerField(default=500, verbose_name='Цена смена ника')),
                (
                'chat_ico_price', models.PositiveSmallIntegerField(default=500, verbose_name='Цена смены иконки чата')),
                ('chat_color_price',
                 models.PositiveSmallIntegerField(default=300, verbose_name='Цена смены цвета чата')),
            ],
            options={
                'verbose_name': '!Настройки модуля пользователей',
                'verbose_name_plural': '!Настройки модуля пользователей',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='chat_color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='user',
            name='ico_num',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер иконки'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='', max_length=50, verbose_name='Статус пользователя'),
        ),
    ]
