# Generated by Django 3.2 on 2021-04-24 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_auto_20210424_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
