# Generated by Django 3.2 on 2021-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_remove_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransaction',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
    ]
