# Generated by Django 3.2 on 2021-04-25 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0016_award_useraward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание награды'),
        ),
        migrations.AlterField(
            model_name='useraward',
            name='award',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.award',
                                    verbose_name='Награда'),
        ),
        migrations.AlterField(
            model_name='useraward',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useraward',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
    ]
