# Generated by Django 3.2 on 2021-04-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_auto_20210425_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraward',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
