# Generated by Django 3.2 on 2021-04-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0020_auto_20210426_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='post_st/inventory/Equipment/addons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='icon',
            field=models.ImageField(blank=True, upload_to='post_st/inventory/Equipment/ammo/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='ammo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grenade',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='grenade',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='grenade',
            name='icon',
            field=models.ImageField(blank=True, upload_to='post_st/inventory/Equipment/grenades/',
                                    verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='grenade',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='armor',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Броня'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='protection',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='pistol',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='pistol',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='pistol',
            name='damage',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Повреждение оружия'),
        ),
        migrations.AlterField(
            model_name='pistol',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pistol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pistolammo',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='pistolammo',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='pistolammo',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pistolammo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upgradeoutfit',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='upgradeoutfit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='upgradeoutfit',
            name='icon',
            field=models.ImageField(blank=True, upload_to='post_st/inventory/Equipment/upgrades_equip/',
                                    verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='upgradeoutfit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upgradeweapon',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='upgradeweapon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='upgradeweapon',
            name='icon',
            field=models.ImageField(blank=True, upload_to='post_st/inventory/Equipment/upgrades_weap/',
                                    verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='upgradeweapon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='cost',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Повреждение оружия'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
