# Generated by Django 3.2 on 2021-04-29 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0022_auto_20210427_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, verbose_name='Описание группировки')),
                ('icon', models.ImageField(help_text='Отображается в профиле пользователя', null=True,
                                           upload_to='users/factions/', verbose_name='Маленькая иконка группировки')),
                ('big_icon', models.ImageField(help_text='Отображается в списке группировок', null=True,
                                               upload_to='users/factions/big/',
                                               verbose_name='Большая иконка группировки')),
                ('power',
                 models.PositiveSmallIntegerField(default=0, help_text='От 0 до 31', verbose_name='Силы группировки')),
                ('er_respect', models.PositiveSmallIntegerField(default=10, verbose_name='Репутация для вступления')),
                ('er_messages', models.PositiveSmallIntegerField(default=10, verbose_name='Сообщений для вступления')),
                ('er_no_bans', models.BooleanField(default=True, verbose_name='Отстутствие замечаний для вступления')),
                ('show_in_list', models.BooleanField(default=True, verbose_name='Отображать в списке групп')),
                ('deputy_leader',
                 models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                      related_name='faction_zam', to=settings.AUTH_USER_MODEL,
                                      verbose_name='Заместитель лидера')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='gr_faction', to='auth.group')),
                ('leader', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                related_name='faction_lead', to=settings.AUTH_USER_MODEL,
                                                verbose_name='Лидер')),
                ('rng_ammo1', models.ManyToManyField(help_text='1 слот', related_name='faction_w_ammo', to='users.Ammo',
                                                     verbose_name='Ассортимент боеприпасов')),
                ('rng_ammo2',
                 models.ManyToManyField(help_text='2 слот', related_name='faction_p_ammo', to='users.PistolAmmo',
                                        verbose_name='Ассортимент боеприпасов')),
                ('rng_outfits', models.ManyToManyField(related_name='faction_bron', to='users.Outfit',
                                                       verbose_name='Ассортимент брони')),
                ('rng_pistols',
                 models.ManyToManyField(help_text='2 слот', related_name='faction_pst', to='users.Pistol',
                                        verbose_name='Ассортимент оружия')),
                ('rng_weapons',
                 models.ManyToManyField(help_text='1 слот', related_name='faction_wpn', to='users.Weapon',
                                        verbose_name='Ассортимент оружия')),
            ],
        ),
    ]
