# Generated by Django 3.2 on 2021-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0023_fraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraction',
            name='er_text',
            field=models.TextField(default='', verbose_name='Дополнительные пожелания'),
        ),
        migrations.AddField(
            model_name='fraction',
            name='сan_entry',
            field=models.BooleanField(default=True, verbose_name='Возможность вступления'),
        ),
    ]
