# Generated by Django 3.2 on 2021-04-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0024_auto_20210429_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraction',
            name='er_text',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительные пожелания'),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='rng_ammo1',
            field=models.ManyToManyField(blank=True, help_text='1 слот', related_name='faction_w_ammo', to='users.Ammo',
                                         verbose_name='Ассортимент боеприпасов'),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='rng_ammo2',
            field=models.ManyToManyField(blank=True, help_text='2 слот', related_name='faction_p_ammo',
                                         to='users.PistolAmmo', verbose_name='Ассортимент боеприпасов'),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='rng_outfits',
            field=models.ManyToManyField(blank=True, related_name='faction_bron', to='users.Outfit',
                                         verbose_name='Ассортимент брони'),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='rng_pistols',
            field=models.ManyToManyField(blank=True, help_text='2 слот', related_name='faction_pst', to='users.Pistol',
                                         verbose_name='Ассортимент оружия'),
        ),
        migrations.AlterField(
            model_name='fraction',
            name='rng_weapons',
            field=models.ManyToManyField(blank=True, help_text='1 слот', related_name='faction_wpn', to='users.Weapon',
                                         verbose_name='Ассортимент оружия'),
        ),
    ]
