# Generated by Django 3.2 on 2021-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0026_user_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
