# Generated by Django 3.2.2 on 2021-05-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0030_auto_20210514_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationformembership',
            name='group',
            field=models.ForeignKey(limit_choices_to={'can_entry': True}, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='users.fraction',
                                    verbose_name='Группа в которую хочет вступить'),
        ),
    ]
