# Generated by Django 3.2.2 on 2021-05-15 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0032_auto_20210516_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationformembership',
            options={'verbose_name': 'Заявка на вступление в группировку',
                     'verbose_name_plural': 'Заявки на вступление в группировку'},
        ),
        migrations.AddField(
            model_name='applicationformembership',
            name='add_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время и дата добавления'),
        ),
        migrations.AddField(
            model_name='applicationformembership',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='application_leader', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Лидер группировки'),
        ),
        migrations.AlterField(
            model_name='applicationformembership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='application_user', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Автор заявления'),
        ),
    ]
