# Generated by Django 3.2.2 on 2021-05-16 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0033_auto_20210516_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationformembership',
            name='banished',
            field=models.BooleanField(default=False, verbose_name='Изгнан'),
        ),
        migrations.AlterField(
            model_name='applicationformembership',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='application_leader', to=settings.AUTH_USER_MODEL,
                                    verbose_name='Лидер группировки'),
        ),
    ]
